name: test
on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: test
        run: chmod +x environment.sh && ./environment.sh test
        shell: bash
